/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
}
